<?php

namespace App\Services;

use App\Repositories\TimesheetRepository;


class TimesheetService extends BaseService
{

    public function __construct(TimesheetRepository $repo)
    {
        parent::__construct($repo);
    }

    public function get($id = null)
    {
       return $this->repo->getUserTimesheet($id); // TODO: Change the autogenerated stub
    }

    /**
     * Group Timesheet records by date on specific user
     */
    public function groupDate($id)
    {
        return $this->repo->groupUserTimesheetByDate($id);
    }

}
