<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('permissions')->delete();

        $permissions = array(
            array('name' => 'department_delete'),
            array('name' => 'department_view'),
            array('name' => 'department_create'),
            array('name' => 'department_update'),
            array('name' => 'designation_delete'),
            array('name' => 'designation_view'),
            array('name' => 'designation_create'),
            array('name' => 'designation_update'),
            array('name' => 'employee_delete'),
            array('name' => 'employee_view'),
            array('name' => 'employee_create'),
            array('name' => 'employee_update'),
            array('name' => 'leave-type_delete'),
            array('name' => 'leave-type_view'),
            array('name' => 'leave-type_create'),
            array('name' => 'leave-type_update'),
            array('name' => 'holiday_delete'),
            array('name' => 'holiday_view'),
            array('name' => 'holiday_create'),
            array('name' => 'holiday_update'),
            array('name' => 'asset-type_delete'),
            array('name' => 'asset-type_view'),
            array('name' => 'asset-type_create'),
            array('name' => 'asset-type_update'),
            array('name' => 'job-type_delete'),
            array('name' => 'job-type_view'),
            array('name' => 'job-type_create'),
            array('name' => 'job-type_update'),
            array('name' => 'job-title_delete'),
            array('name' => 'job-title_view'),
            array('name' => 'job-title_create'),
            array('name' => 'job-title_update'),
            array('name' => 'organization-category_delete'),
            array('name' => 'organization-category_view'),
            array('name' => 'organization-category_create'),
            array('name' => 'organization-category_update'),
            array('name' => 'organization-group_delete'),
            array('name' => 'organization-group_view'),
            array('name' => 'organization-group_create'),
            array('name' => 'organization-group_update'),
            array('name' => 'stakeholder_delete'),
            array('name' => 'stakeholder_view'),
            array('name' => 'stakeholder_create'),
            array('name' => 'stakeholder_update'),
            array('name' => 'individual-group_delete'),
            array('name' => 'individual-group_view'),
            array('name' => 'individual-group_create'),
            array('name' => 'individual-group_update'),
            array('name' => 'individual_delete'),
            array('name' => 'individual_view'),
            array('name' => 'individual_create'),
            array('name' => 'individual_update'),
            array('name' => 'experience_delete'),
            array('name' => 'experience_view'),
            array('name' => 'experience_create'),
            array('name' => 'experience_update'),
            array('name' => 'resource-people_delete'),
            array('name' => 'resource-people_view'),
            array('name' => 'resource-people_create'),
            array('name' => 'resource-people_update'),
            array('name' => 'event-category_delete'),
            array('name' => 'event-category_view'),
            array('name' => 'event-category_create'),
            array('name' => 'event-category_update'),
            array('name' => 'event_delete'),
            array('name' => 'event_view'),
            array('name' => 'event_create'),
            array('name' => 'event_update'),
            array('name' => 'participant-role_delete'),
            array('name' => 'participant-role_view'),
            array('name' => 'participant-role_create'),
            array('name' => 'participant-role_update'),
            array('name' => 'participant_delete'),
            array('name' => 'participant_view'),
            array('name' => 'participant_create'),
            array('name' => 'participant_update'),
            array('name' => 'item-category_delete'),
            array('name' => 'item-category_view'),
            array('name' => 'item-category_create'),
            array('name' => 'item-category_update'),
            array('name' => 'item-unit_delete'),
            array('name' => 'item-unit_view'),
            array('name' => 'item-unit_create'),
            array('name' => 'item-unit_update'),
            array('name' => 'item_delete'),
            array('name' => 'item_view'),
            array('name' => 'item_create'),
            array('name' => 'item_update'),
            array('name' => 'item-in_delete'),
            array('name' => 'item-in_view'),
            array('name' => 'item-in_create'),
            array('name' => 'item-in_update'),
            array('name' => 'item-request_delete'),
            array('name' => 'item-request_view'),
            array('name' => 'item-request_create'),
            array('name' => 'item-request_update'),
            array('name' => 'item-issue_delete'),
            array('name' => 'item-issue_view'),
            array('name' => 'item-issue_create'),
            array('name' => 'item-issue_update'),
            array('name' => 'role_delete'),
            array('name' => 'role_view'),
            array('name' => 'role_create'),
            array('name' => 'role_update'),
            array('name' => 'permission_view'),
            array('name' => 'permission_create'),
            array('name' => 'permission_update'),
            array('name' => 'permission_delete'),
            array('name' => 'location_update'),
            array('name' => 'location_view'),
            array('name' => 'location_create'),
            array('name' => 'location_delete'),
            array('name' => 'user_update'),
            array('name' => 'user_view'),
            array('name' => 'user_create'),
            array('name' => 'user_delete'),
        );


        foreach($permissions as $permission){
            Permission::create($permission);
        }
    }
}
