<?php

namespace App\Services;

use App\Repositories\EventRepository;

class EventService extends BaseService
{

    public function __construct(EventRepository $repo)
    {
        parent::__construct($repo);
    }


    public function get()
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }

    /**
     * Get Total Event Participants
     */
    public function getEventParticipants()
    {
        return $this->repo->getEventParticipants();
    }

    /**
     * Get Name and Event duration
     */
    public function getNameAndDuration()
    {
        return $this->repo->getNameAndDuration();
    }


}
