@extends('layouts.templates.finance')
@section('title','Vouchers List')
@section('content')

    <div class="row justify-content-center voucher">
        <div class="col-md-8">
            <x-card title="View Voucher">
                <table style="border: none;border-collapse: collapse;width:529pt;">
                    <tbody>
                    <tr>
                        <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:none;height:21.0pt;width:48pt;"><br></td>
                        <td colspan="6" style='color:black;font-size:19px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;width:433pt;'>TANZANIA GENDER NETWORKING PROGRAMME</td>
                        <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:none;width:48pt;"><br></td>
                    </tr>
                    <tr>
                        <td colspan="2" style='color:windowtext;font-size:19px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:21.0pt;'></td>
                        <td colspan="4" style='color:windowtext;font-size:19px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:.5pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'>Cheque Payment Voucher</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:.5pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:21.0pt;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:19px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:none;"><br></td>
                        <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:none;"><br></td>
                        <td style='color:windowtext;font-size:19px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:20.25pt;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'>PAYEE</td>
                        <td style='color:windowtext;font-size:19px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:19px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:19px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>Voucher No:<span style='color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;'>&nbsp;</span></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'>Name:&nbsp;</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>Date:</td>
                        <td style='color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'>22.12.2020</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'>Adress;</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>Transaction Type:</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'>Telephone No:&nbsp;</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="4" style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:top;border:none;border-top:none;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;height:17.25pt;width:192pt;'>Adress;</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;width:48pt;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;width:48pt;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="4" style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:top;border:none;border-top:none;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;height:17.25pt;width:192pt;'>SHAMIRA MSHANGAMA</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>Cheque No:</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:23.25pt;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;'><br></td>
                        <td style='color:windowtext;font-size:21px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'>*003125</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="2" style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'>Bank Account:</td>
                        <td colspan="2" style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid black;border-bottom:none;border-left:none;'>TSHS ACCOUNT</td>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>Currency:&nbsp;</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'>TSHS</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="2" style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'>Bank Account No:</td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:left;vertical-align:bottom;border:none;border-right:1.0pt solid black;'>2001-004</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:left;vertical-align:bottom;border:none;'><br></td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>Exchange Rate:</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:left;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="8" style='color:black;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:top;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;height:15.75pt;width:529pt;'>BEING AMOUNT PAID AS MODERATION FEE ON 16 DAYS OF ACTIVISM LESS W/TAX OF TSHS 15,000/=</td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="2" style='color:windowtext;font-size:16px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:18.0pt;'>Particulars</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:.5pt solid windowtext;border-bottom:none;border-left:none;'>Account: code</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:1.0pt solid windowtext;border-top:none;'>Cash book Amount</td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:1.0pt solid windowtext;border-top:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:windowtext;font-size:11px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid black;border-bottom:1.0pt solid windowtext;border-left:  none;'><br></td>
                        <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;">285,000.00</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="4" style='color:black;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;width:192pt;'><br></td>
                        <td colspan="2" style='color:black;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:.5pt solid windowtext;border-left:none;'><br></td>
                        <td style="color:windowtext;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:none;text-align:right;border-top:none;border-right:1.0pt solid windowtext;border-bottom:.5pt solid windowtext;border-left:none;"><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:.5pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td colspan="2" style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:left;vertical-align:bottom;border:none;border-top:.5pt solid windowtext;border-right:1.0pt solid black;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style="color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:.5pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;border-top:none;"><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:.5pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;border-top:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td colspan="2" style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid black;border-bottom:1.0pt solid windowtext;border-left:none;'>Home Currency Total</td>
                        <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;">285,000.00</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'>Total</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;">285,000.00</td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;border-top:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="3" style='color:black;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid black;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:17.25pt;'>TOTAL IN WORDS:</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="8" rowspan="2" style='color:black;font-size:13px;font-weight:700;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:top;border:none;border-top:1.0pt solid windowtext;border-right:  1.0pt solid black;border-bottom:1.0pt solid black;border-left:1.0pt solid windowtext;height:30.75pt;width:529pt;'>TWO HUNDRED EIGHTY FIVE THOUSAND &nbsp;ONLY</td>
                    </tr>
                    <tr></tr>
                    <tr>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'>PREPARED BY;</td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid black;border-bottom:none;border-left:none;'>REVIEWED BY</td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'>APPROVED BY</td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>AUTHORIZED BY</td>
                        <td style='color:windowtext;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="2" style='color:black;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;height:17.25pt;'>ELIETH JOSEPHAT</td>
                        <td colspan="2" style='color:black;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-right:1.0pt solid black;'>ALTHO MWANGOA</td>
                        <td colspan="2" style='color:black;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'>ANNA KIKWA</td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;'>ED: LILIAN LIUNDI</td>
                        <td style='color:windowtext;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:1.0pt solid windowtext;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'>Sign&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;.</td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;'>Sign&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;.</td>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>Sign&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;.</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;'>Sign&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;.</td>
                        <td style='color:windowtext;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td>
                        <td style='color:windowtext;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td colspan="2" style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid black;border-bottom:none;border-left:1.0pt solid windowtext;height:16.5pt;'>RECEIVED BY</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'>Date;</td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'>ID/Tel no</td>
                        <td style='color:windowtext;font-size:12px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:none;border-left:1.0pt solid windowtext;height:15.75pt;'>Name:</td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                        <td colspan="2" style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-right:1.0pt solid black;'>Signature&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;..</td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:black;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;'><br></td>
                        <td style='color:windowtext;font-size:13px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;'><br></td>
                    </tr>
                    <tr>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:1.0pt solid windowtext;height:17.25pt;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:none;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                        <td style='color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:"Arial Unicode MS", sans-serif;text-align:general;vertical-align:bottom;border:none;border-top:none;border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;border-left:none;'><br></td>
                    </tr>
                    </tbody>
                </table>
            </x-card>
        </div>
    </div>
@endsection
