<?php

namespace App\Repositories;

use App\Models\JobTitle;
use App\Models\Location;
use App\Models\Experience;
use Illuminate\Support\Facades\DB;

class ExperienceRepository extends BaseRepository
{
    /**
     * @var Location
     */
    protected $location;
    protected $title;

    /**
     * ExperienceRepository constructor.
     */
    public function __construct(Experience $model)
    {
        parent::__construct($model);
        $this->location = new Location;
        $this->title = new JobTitle;
    }

    /**
     * Get Model Collection with relationship
     */
    public function withRelation($id = null)
    {
        return $this->model
            ->whereNotIn('organization_id',$id)
            ->with([
                'individual',
                'organization',
                'job_title',
                'location'])
            ->get();
    }

    /**
     * Update Data
     */
    public function updateData($id, $request)
    {
        return $this->update($id, $request); // TODO: Change the autogenerated stub
    }

    /**
     * Get all the members from the specific organization
     */
    public function getOrganizationExperienceMember($org)
    {
        return $this->model
            ->with([
                'individual',
                'organization',
                'job_title',
                'location'])
            ->where('experiences.organization_id',$this->decodable($org))
            ->get();
    }

    /**
     * Get List of KC Members
     */
    public function getKCMembersList($id)
    {
        return $this->model
            ->whereIn('organization_id',$id)
            ->with([
                'individual',
                'organization',
                'job_title',
                'location'])
            ->get();
    }
}
