<?php

namespace App\Repositories;

use App\Models\GenderSeries;

class GenderSeriesRepository extends BaseRepository
{
    public function __construct(GenderSeries $model)
    {
        parent::__construct($model);
    }


    /**
     * Manage Event Facilitator
     */
    public function facilitator($gender , $request, $update = null)
    {
        if(!is_null($gender)) {
            return $gender->facilitator()->sync($request);
        }
        else {
            return $gender->facilitator()->attach($request);
        }
    }

    public function updateData($id, $request)
    {
        return $this->update($id,$request); // TODO: Change the autogenerated stub
    }

    /**
     * Get Gender series List
     */
    public function dropdownList()
    {
        return $this->model->select('id','topic','date')->orderBy('date','asc')->get();
    }

}
