<?php

namespace App\Repositories;

use App\Models\Project;

class ProjectRepository extends BaseRepository
{
    public function __construct(Project $model)
    {
        parent::__construct($model);
    }

    /**
     * Get Event with Relation
     */
    public function get()
    {
        return $this->model->with([
            'stakeholder'=>function($query){
                $query->with('organization')->get();
            },
            'coordinator',
        ])->get();
    }

    /**
     * `
     * `
     */
    public function updateData($id, $request)
    {
        return $this->update($id, $request); // TODO: Change the autogenerated stub
    }

    /**
     * Manage Project Coordinator
     */
    public function coordinator($project , $request, $update = null)
    {
        if(!is_null($update)) {
            return $project->coordinator()->sync($request);
        }
        else {
            return $project->coordinator()->attach($request);
        }
    }

}
